### PR TITLE
Marked strings as translatable

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @UdoBretz 
I found some strings, which are not marked for translation. Can you sync with Transifex after commit?

### CODE REVIEW

**Comment by urbalazs** [comment]
Hi @UdoBretz 
Can you check this PR? This marks several strings for translation.

**Comment by urbalazs** [comment]
Hi @UdoBretz 
Can you check this PR? Now there are many untranslated strings in the user interface. This PR makes it better. Please sync with Transifex after commit.

**Comment by urbalazs** [comment]
Hi @UdoBretz 
Any news about this PR?

**Comment by urbalazs** [comment]
Hi @UdoBretz 
Any news? This is only translation improvement, no logic is changed.

**Comment by UdoBretz** [comment]
Hi @urbalazs,

thanks for your pull request, it has just been merged.

Thanks, and best regards,
Udo

**Pull request closed without merging**
